"""Creation tools: build abilities, adversaries, and operations.

Names are auto-generated by :mod:`naming` (deterministic, ATT&CK-aligned) and
de-duplicated against what already exists. Each tool reuses Caldera's own v2 API
managers / rest service so created artefacts persist to disk and behave exactly
like ones made in the Caldera UI.

Operations are created in the ``paused`` state so creation and execution stay
separate — ``start_operation`` (a later step) launches them.

This file is original to the claudera plugin (Apache-2.0).
"""

from __future__ import annotations

from app.api.v2.managers.ability_api_manager import AbilityApiManager
from app.api.v2.managers.adversary_api_manager import AdversaryApiManager
from app.objects.c_ability import Ability
from app.objects.c_adversary import Adversary
from app.utility.base_world import BaseWorld

from .. import naming
from . import Registry, ToolContext, ToolSpec


def _access_for(ctx: ToolContext) -> dict:
    """Build the Caldera access dict for the caller's group."""
    group = (ctx.group or "").lower()
    if group == "blue":
        return {"access": [BaseWorld.Access.BLUE]}
    return {"access": [BaseWorld.Access.RED]}


async def _existing_names(ctx: ToolContext, ram_key: str) -> list[str]:
    return [o.name for o in await ctx.services["data_svc"].locate(ram_key)]


# -- create_ability -----------------------------------------------------------

async def _create_ability(ctx: ToolContext, args: dict) -> dict:
    data_svc = ctx.services["data_svc"]
    file_svc = ctx.services["file_svc"]

    summary = args.get("summary") or args.get("description")
    name = naming.deduplicate(
        naming.ability_name(args["technique_id"], summary),
        await _existing_names(ctx, "abilities"),
    )
    cleanup = args.get("cleanup")
    data = {
        "ability_id": "",
        "name": name,
        "tactic": args["tactic"],
        "technique_id": naming.normalize_technique_id(args["technique_id"]),
        "technique_name": args.get("technique_name") or "",
        "description": args.get("description") or "",
        "executors": [
            {
                "name": args["executor"],
                "platform": args["platform"],
                "command": args["command"],
                "cleanup": [cleanup] if cleanup else [],
                "payloads": list(args.get("payloads") or []),
                "timeout": int(args.get("timeout", 60)),
            }
        ],
        "requirements": list(args.get("requirements") or []),
        "privilege": args.get("privilege"),
        "singleton": bool(args.get("singleton", False)),
    }
    manager = AbilityApiManager(data_svc, file_svc)
    ability = await manager.create_on_disk_object(data, _access_for(ctx), "abilities", "ability_id", Ability)
    return {
        "status": "created",
        "ability_id": ability.ability_id,
        "name": ability.name,
        "tactic": ability.tactic,
        "technique_id": ability.technique_id,
        "executors": [f"{e.platform}/{e.name}" for e in ability.executors],
    }


# -- create_adversary ---------------------------------------------------------

async def _create_adversary(ctx: ToolContext, args: dict) -> dict:
    data_svc = ctx.services["data_svc"]
    file_svc = ctx.services["file_svc"]

    ability_ids = list(args.get("ability_ids") or [])
    if not ability_ids:
        raise ValueError("ability_ids must contain at least one ability id (ordered)")
    known = {a.ability_id for a in await data_svc.locate("abilities")}
    missing = [aid for aid in ability_ids if aid not in known]
    if missing:
        raise ValueError(f"unknown ability id(s): {', '.join(missing)}")

    name = naming.deduplicate(
        naming.adversary_name(args.get("theme", ""), args.get("description", "")),
        await _existing_names(ctx, "adversaries"),
    )
    data = {
        "adversary_id": "",
        "name": name,
        "description": args.get("description") or "",
        "atomic_ordering": ability_ids,
    }
    manager = AdversaryApiManager(data_svc, file_svc)
    adv = await manager.create_on_disk_object(data, _access_for(ctx), "adversaries", "adversary_id", Adversary)
    return {
        "status": "created",
        "adversary_id": adv.adversary_id,
        "name": adv.name,
        "ability_count": len(adv.atomic_ordering),
        "atomic_ordering": list(adv.atomic_ordering),
    }


# -- create_operation ---------------------------------------------------------

async def _create_operation(ctx: ToolContext, args: dict) -> dict:
    data_svc = ctx.services["data_svc"]
    rest_svc = ctx.services["rest_svc"]

    adversary_id = args["adversary_id"]
    advs = await data_svc.locate("adversaries", match=dict(adversary_id=adversary_id))
    if not advs:
        raise ValueError(f"unknown adversary_id: {adversary_id}")
    adversary = advs[0]
    group = args["group"]
    planner = args.get("planner", "atomic")
    source = args.get("source", "basic")

    name = naming.deduplicate(
        naming.operation_name(adversary.name, group),
        await _existing_names(ctx, "operations"),
    )
    data = {
        "name": name,
        "group": group,
        "adversary_id": adversary_id,
        "planner": planner,
        "source": source,
        # Create paused so creation and execution are separate concerns.
        "state": "paused",
    }
    operation = await rest_svc._build_operation_object(_access_for(ctx), data)
    operation.set_start_details()
    await data_svc.store(operation)
    return {
        "status": "created_paused",
        "operation_id": operation.id,
        "name": operation.name,
        "state": operation.state,
        "adversary": adversary.name,
        "group": group,
        "planner": planner,
        "source": source,
        "note": "Operation created in 'paused' state; use start_operation to launch it.",
    }


# -- registration -------------------------------------------------------------

_NAMING_NOTE = (
    "Names are auto-generated and must not be supplied. Ability names are "
    "T####[.###]_<short_snake_desc>, adversaries <theme>_<short_desc>, operations "
    "op_<adversary>_<group>_<UTCstamp>. Keep summaries short and descriptive."
)


def register(registry: Registry) -> None:
    registry.add(
        ToolSpec(
            name="create_ability",
            description=(
                "Create a Caldera ability (a single ATT&CK technique action). " + _NAMING_NOTE
            ),
            input_schema={
                "type": "object",
                "properties": {
                    "technique_id": {"type": "string", "description": "ATT&CK technique id, e.g. T1059.001"},
                    "tactic": {"type": "string", "description": "ATT&CK tactic, e.g. execution"},
                    "platform": {"type": "string", "description": "windows | linux | darwin"},
                    "executor": {"type": "string", "description": "Executor name, e.g. psh, cmd, sh, pwsh, proc"},
                    "command": {"type": "string", "description": "The command to run."},
                    "description": {"type": "string", "description": "Full description of what the ability does."},
                    "summary": {"type": "string", "description": "Short summary used to name the ability (optional; defaults to description)."},
                    "technique_name": {"type": "string"},
                    "cleanup": {"type": "string", "description": "Optional cleanup command."},
                    "payloads": {"type": "array", "items": {"type": "string"}, "description": "Payload file names the executor references."},
                    "requirements": {"type": "array", "items": {"type": "object"}},
                    "privilege": {"type": "string", "description": "Elevated | User (optional)."},
                    "timeout": {"type": "integer"},
                    "singleton": {"type": "boolean"},
                },
                "required": ["technique_id", "tactic", "platform", "executor", "command", "description"],
                "additionalProperties": False,
            },
            handler=_create_ability,
            mutating=True,
        )
    )
    registry.add(
        ToolSpec(
            name="create_adversary",
            description=(
                "Create a Caldera adversary profile from an ordered list of ability ids. " + _NAMING_NOTE
            ),
            input_schema={
                "type": "object",
                "properties": {
                    "theme": {"type": "string", "description": "Adversary theme, e.g. hyadina."},
                    "description": {"type": "string", "description": "Short description of the adversary chain."},
                    "ability_ids": {"type": "array", "items": {"type": "string"}, "description": "Ordered ability ids to run."},
                },
                "required": ["ability_ids"],
                "additionalProperties": False,
            },
            handler=_create_adversary,
            mutating=True,
        )
    )
    registry.add(
        ToolSpec(
            name="create_operation",
            description=(
                "Create (but do not start) a Caldera operation from an adversary, agent group, "
                "planner, and fact source. Created in the 'paused' state. " + _NAMING_NOTE
            ),
            input_schema={
                "type": "object",
                "properties": {
                    "adversary_id": {"type": "string"},
                    "group": {"type": "string", "description": "Agent group to target."},
                    "planner": {"type": "string", "description": "Planner name (default: atomic)."},
                    "source": {"type": "string", "description": "Fact source name (default: basic)."},
                },
                "required": ["adversary_id", "group"],
                "additionalProperties": False,
            },
            handler=_create_operation,
            mutating=True,
        )
    )
